name = "settings"
name_pretty = "Settings"
icon = "applications-other"

[[entries]]
text = "Audio Settings"
actions = {"open" = "pwvucontrol"}

[[entries]]
text = "Change wallpaper"
actions = {"open" = "waypaper"}

[[entries]]
text = "Task manager"
actions = {"open" = "gnome-system-monitor"}
