force_keyboard_focus = true
selection_wrap = true
hide_action_hints = true
theme = "custom"

[columns]
symbols = 1

[providers]
default = [
  "desktopapplications",
  "calc",
  "runner",
  "websearch",
]

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = ">"
provider = "runner"

[[providers.prefixes]]
prefix = "?"
provider = "websearch"

[providers.clipboard]
time_format = "%d.%m. - %H:%M"