
[general]
live_config_reload = true
import = ["./theme.toml"]

[window.padding]
x = 5
y = 5

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Italic"

[cursor.style]
shape = "Beam"
blinking = "Off"
